### PR TITLE
Corrections to read/write xml routines and ed_params

### PR DESCRIPTION
**Pull request by fabeit**
I have moved pft radiative parameters from radiate_driver to ed_params.
These parameters are calculated only once per run. Also corrected errors
in xml read/write routines and moved write xml routine just before time
integration starts. Now the .xml is always being written regardless if
an input xml is provided or not. I commented variables in
canopy_radiations_coms which are not used.

### CODE REVIEW

**Comment by serbinsh** [comment]
@Viskari @mdietze Any worries about this PR affecting EDR?  @Viskari do we need to update EDR radiate_driver such that is matches these changes?  We need to make sure everything stays consistent and that EDR still works as needed after these xml changes

**Comment by serbinsh** [comment]
@Viskari it looks like these changes should not affect EDR but possibly improve however lets be sure....

**Comment by fabeit** [comment]
I have made further changes, should I cancel this PR and create a new one?

**Comment by serbinsh** [comment]
You can update your current PR if you just push the new changes under the same branch.

S
------------------------------------------------------------------------
Shawn P. Serbin
Environmental & Climate Sciences Department
Brookhaven National Laboratory
Upton, NY 11973-5000

Phone: +1-631-344-3165
Fax: +1-631-344-2060
Email: sserbin@bnl.gov<mailto:sserbin@bnl.gov>
Bio:  http://www.bnl.gov/envsci/bio/serbin-shawn.php
TEST Group: http://www.bnl.gov/TEST/
Twitter: @doctorjackpine, @test_bnl
------------------------------------------------------------------------

On Aug 16, 2016, at 9:45 AM, fabeit <notifications@github.com<mailto:notifications@github.com>> wrote:


I have made further changes, should I cancel this PR and create a new one?

**Comment by fabeit** [comment]
@serbinsh I tried to do that but it doesn't seem to work, what command do you use?

**Comment by mdietze** [comment]
There was a small bug in the Travis yml file that controls the build test. I fixed it in the mainline -- if you pull the mainline and push back up to github it should pull in the fix and trigger a restart of the build check.

**Comment by crollinson** [comment]
@fabeit It looks like you might need to close this pull request or start a separate branch.  I started getting notifications about elephant disturbance that I think there should be a discussion about that appear to be only tangentially-related to this 2-year old PR.

**Comment by fabeit** [comment]
@crollinson sorry I didn't realize this, I just wanted to update the file in my local branch. I have closed the pull request.

**Pull request closed without merging**
