### PR TITLE
Bugfix for if statement comparing logical with integer

### PR DESCRIPTION
**Pull request by Viskari**
Hello,

 The existing disturbance.f90 had a bug in it, as due to an apparent typo there was a comparison of a logical and integer. Corrected here.

### CODE REVIEW

**Comment by robkooper** [comment]
The other option that seemed to work for me is:
if (include_pft(ipft) .EQV. (cpatch%pft(1) == 1)) then

**Comment by mdietze** [comment]
@Viskari I was going to go ahead and process this pull, but on 5/7 you added a whole bunch of radiation stuff to the commit as well that's not related to this issue. Could you rollback that second commit and I'll merge the rest immediately

**Comment by Viskari** [comment]
I didn't realize that I added anything since I didn't do the pull request
after pushing the radiation scheme.

How do I rollback the second commit?

**Comment by mdietze** [comment]
Cherry-picked just commit f9b6fc08b93b8112319673b42063d57670336c12 and pushed directly to master

**Pull request closed without merging**
