### PR TITLE
Sserbin.updated hdf5

### PR DESCRIPTION
**Pull request by serbinsh**
Updated default HDF5 on modex.bnl.gov

### CODE REVIEW

**Comment by serbinsh** [comment]
@mdietze @mpaiao not sure why travis failed on my PR.  All I changed was the HDF version in the include file for BNL.....so not sure if this is a travis issue or something related to a previous PR?

**Comment by serbinsh** [comment]
It looks like a bug in the travis config for building ED

**Comment by fabeit** [comment]
My PR also failed right away. Probably something wrong.

**Comment by serbinsh** [comment]
@mdietze could you also commit this PR?  It should impact anyone but will make building on our server easier...thanks!

**Comment by serbinsh** [comment]
@mdietze never mind.....It looks like I did this awhile ago

**Pull request closed without merging**
