### PR TITLE
New photosynthesis variables

### PR DESCRIPTION
**Pull request by mpaiao**
A few diagnostic variables for photosynthesis following issue #85 :
?mean_a_open: assimilation rate if soil moisture was not constraining photosynthesis (not really "open stomata" because VPD and light may close them)
?mean_a_closed: assimilation rate if stomata were closed
?mean_a_net: assimilation scaled by fsw.

PS:  First time I split my working directory in branches, not sure if it works.  Let me know if the pull request has more stuff than it should (esp. changes in allometry).

### CODE REVIEW

**Comment by mdietze** [comment]
@mpaiao  FYI, in addition to the photosynthetic variable changes, this pull request included a ton of changes/additions to various R files as well as a lot of changes to radiate_driver.f90 (too big for github's diff to visualize on the webpage). The R changes don't affect ED itself, and the variable additions look straightforward, but could you clarify what the radiate_driver changes were?

**Comment by mpaiao** [comment]
@mdietze The R scripts are mostly for post-processing.  Some people in Paul's lab used to use these scripts, but I think I'm the only one using it nowadays.  We could probably take them out of ED2 git, and I could create a git version on my account. 

I went through radiate_driv.f90 again on my local machine using Linux's "diff -ib", and there is no real code difference.  Some recent commit added extra spaces in the beginning of every line of the code, and I simply removed them.  I also remove a few obsolete allocate/deallocate statements that have been commented out for a while; I think it's safer to delete them, just to avoid memory leaks in case they were accidentally uncommented.

**Comment by mdietze** [comment]
@mpaiao OK. I'm fine with including the R scripts -- you just specifically asked if the pull request had things in it other than the output variables.

@rgknox do you want to go ahead and merge this? Doesn't change any internal calculations so it shouldn't need the full test suite

**Comment by serbinsh** [comment]
@mdietze @rgknox @mpaiao 

What is the status of this merge?  Are we ready to make it so?

**Comment by mpaiao** [comment]
@serbinsh Yeah, I think it's ready to merge, these are very minor changes to the code.

**Pull request merged**
