### PR TITLE
Fix MPI compiling fail

### PR DESCRIPTION
**Pull request by crollinson**
Per Issue #210 

Not the full fix with the MPI-specific flags, but it allows non-intel MPI compiling to work.

Also a little tweak to allow >1000 yrs of land use change drivers.

### CODE REVIEW

**Comment by manfredo89** [comment]
I think most changes are ok. Though I don't think we should reintroduce ioptinpt. As it is now the code would not compile since the file memory/optimiz_coms.f90 where the module is declared is no longer. I can see that it is called by MPI_Bcast but since the variable ioptinpt was not set (was '' in ED2IN) I don't see how it could have been of any use.
I think the easy fix is simply to delete this two calls, however I am not an expert on MPI (my understanding is that ioptinpt was just broadcasted to the nodes, so the calls can be deleted).

**Comment by mpaiao** [comment]
I agree, the MPI_Bcast calls that have ioptinpt (two of them) should be removed in ed_mpass_init.F90.

**Comment by crollinson** [comment]
I do get this error, but the program does seem to compile and run at least with very rudimentary tests `*** No rule to make target 'optimiz_coms.mod', needed by 'ed_mpass_init.o'.  Stop.`

**Comment by mpaiao** [comment]
I can think of two possibilities...
1. You had some optimiz_coms file from a prior compilation
2. There are some calls to optimiz_coms in rules.mk 

Does the problem show even when you compile from scratch?

**Comment by crollinson** [comment]
My guess is there's a optimized_coms in rules.mk since I always do clean installs

**Pull request merged**
