### PR TITLE
Build tweaks

### PR DESCRIPTION
**Pull request by DanielNScott**
Changes:
See #155 

- Only one build directory, build
- install.sh supports key-word options such as: ```install.sh --kind A --platform odyssey``` or ```install.sh --clean```. ```install.sh``` defaults to ```install.sh --kind E --platform gfortran```
- built executables, "bin" directories, and the library file are tagged with compilation kind, dbg or opt, git branch, and git commit number. This can be turned off with
   ```install.sh --gitoff``` or ```install.sh -g```

Here's an example:
```
dscott@rclogin03:/n/moorcroftfs4/dscott/code/ed_ml/ED/build=>ls
total 528K
drwxr-sr-x 2 dscott moorcroft_lab 4.0K Mar 29 15:01 make
drwxr-sr-x 2 dscott moorcroft_lab  150 Mar 29 14:34 shell
-rw-r--r-- 1 dscott moorcroft_lab 509K Mar 29 14:34 morph_tab.binary
-rw-r--r-- 1 dscott moorcroft_lab 2.2K Mar 29 14:34 NCSA.instructions.README
-rwxr-xr-x 1 dscott moorcroft_lab 4.5K Mar 29 15:25 install.sh
dscott@rclogin03:/n/moorcroftfs4/dscott/code/ed_ml/ED/build=>install.sh --kind A --platform odyssey
[...]
dscott@rclogin03:/n/moorcroftfs4/dscott/code/ed_ml/ED/build=>ls
total 384M
drwxr-sr-x 2 dscott moorcroft_lab  48K Mar 29 16:17 dbgbin-A-build-tweaks-aca6b00
drwxr-sr-x 2 dscott moorcroft_lab 4.0K Mar 29 15:01 make
drwxr-sr-x 2 dscott moorcroft_lab  150 Mar 29 14:34 shell
-rwxr-xr-x 1 dscott moorcroft_lab 122M Mar 29 16:17 ed_2.1-dbg-build-tweaks-aca6b00
-rw-r--r-- 1 dscott moorcroft_lab 179M Mar 29 16:17 ed_2.1-dbg-build-tweaks-aca6b00.a
-rw-r--r-- 1 dscott moorcroft_lab 509K Mar 29 14:34 morph_tab.binary
-rw-r--r-- 1 dscott moorcroft_lab 2.2K Mar 29 14:34 NCSA.instructions.README
-rwxr-xr-x 1 dscott moorcroft_lab 4.5K Mar 29 15:25 install.sh
```

### CODE REVIEW

**Comment by DanielNScott** [comment]
Actually, aca6b00 didn't pass the build check, so I'll need to fix that.
Also, this works for me but I can only test a limited number of the platforms.

**Comment by mdietze** [comment]
@crollinson could you test this branch on our server and give Dan a thumbs up to thumbs down?

**Comment by crollinson** [comment]
I’ll do it next week when I’m back from Argentina...  Limited (and slow) internet availability down here.

**Comment by DanielNScott** [comment]
Hey @crollinson, did you get a chance to check this out?

**Comment by crollinson** [comment]
Sorry for the delay @DanielNScott.  Your changes work on BU's geo (Linux CentOS, I think).

**Comment by DanielNScott** [comment]
Great, thanks for checking!

**Pull request merged**
