### PR TITLE
Adjusting ED2 output for pecan

### PR DESCRIPTION
**Pull request by Viskari**
-Added keys in ed_state_vars.f90 so that FMEAN_* variables are written in the tower output file.
-Added an output variable for FMEAN_A_OPEN_PY and FMEAN_A_CLOSED_PY
-Created new variables for FMEAN_BDEAD_PY and FMEAN_LAI_PY required by pecan.

### CODE REVIEW

**Comment by mdietze** [comment]
@rgknox I looked through this code and I don't see any issues.

**Comment by serbinsh** [comment]
@Viskari @mdietze @rgknox Where are we on this?  Have these changes been incorporated? @Viskari have you made the needed modifications to the XML code yet so that rad properties are properly read during PEcAn runs?

**Comment by Viskari** [comment]
Yeah, everything necessary is included in the current pull request.

**Comment by mdietze** [comment]
Trying to address the pile of pending pull requests and having just done a few other pulls there's now a conflict on this one.  Could  you resolve and update the pull request?

**Comment by Viskari** [comment]
Sure, but how do I see what is causing the conflict?

**Comment by mdietze** [comment]
Just pull the latest code off github and git will automatically flag the files that have conflicts and put <<<<, =====, and >>>>> sections around the actual bits of code that cause conflicts. You'll need to resolve those conflicts before you can commit the code, but once you do that and push back to github this pull request should be automatically updated

**Comment by Viskari** [comment]
But it doesn't show anything. It just gives the following message:

[tviskari@modex ED2]$ git pull upstream master
From github.com:EDmodel/ED2
 * branch            master     -> FETCH_HEAD
error: Your local changes to 'ED/src/dynamics/radiate_driver.f90' would be
overwritten by merge.  Aborting.
Please, commit your changes or stash them before you can merge.

Which is confusing since when I checked, the latest changes in that file
are the changes I made and my current pull request doesn't have anything
from that.

**Comment by robkooper** [comment]
This means you have edits in your code that have not been committed. You can see this with the command git status which will list all files you have modified but not committed. You can use the following set of command to fix this.

```
git stash
git pull upstream master
# fix errors if any
git commit
git push
git stash pop
```

git stash will store your changes in a temporary commit, and git stash pop will get the last set of changes you did.

**Comment by Viskari** [comment]
Okay, I'll try that, but I am still confused as I haven't changed anything
in that file. The only thing I can think was that I had it print out some
infor during run a while back, but even that I removed from the current
file.

**Comment by serbinsh** [comment]
Might be as simple as a mismatch of line numbers if you added in some print statements (and thus total line numbers increased) and removing resulted in a mismatch.  However, usually those simple differences are handled automatically.

S
------------------------------------------------------------------------------
Shawn P. Serbin
Biological, Environmental & Climate Sciences Department
Brookhaven National Laboratory
Upton, NY 11973-5000

Phone: +1-631-344-3165
Fax: +1-631-344-2060
Email: sserbin@bnl.gov<mailto:sserbin@bnl.gov>
Bio:  http://www.bnl.gov/envsci/bio/serbin-shawn.php
TEST Group: http://www.bnl.gov/TEST/
Twitter: @doctorjackpine, @test_bnl
------------------------------------------------------------------------------

On Jul 29, 2015, at 3:12 PM, Viskari <notifications@github.com<mailto:notifications@github.com>> wrote:

Okay, I'll try that, but I am still confused as I haven't changed anything
in that file. The only thing I can think was that I had it print out some
infor during run a while back, but even that I removed from the current
file.

**Comment by apourmok** [comment]
You can always use "git log" to see the whole history of what changed by whom. That worked for me.

**Comment by DanielNScott** [comment]
and of course 'git diff file1 file2' and 'git status' ...

**Comment by Viskari** [comment]
According to git, the files can now be merged.

**Pull request merged**
