### PR TITLE
Update ed_type_init.f90

### PR DESCRIPTION
**Pull request by Lo-hatch**
Maybe Wrong initiation for sla and sla_toc when phenology==3?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

## Testing :

- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Lo-hatch** [comment]
The initialiation of SLA in ed_params:
   SLA(:) = merge(sla_s0(:), sla_s0(:)* leaf_turnover_rate(:)**sla_s1(:), leaf_turnover_rate(:)*sla_s1(:) == 0)
But the  initialiation of sla and sla_toc in ed_type_init:
 cpatch%sla   (ico) = sla_s0(ipft) * cpatch%llspan(ico) ** sla_s1(ipft)
  that wrongly makes the sla of late successional pft > middle successional  > early successional.

**Comment by xiangtaoxu** [comment]
@mpaiao , based on the codes and the value of sla_s1 (positive), SLA will indeed be larger for late-successional PFT which has longer llspan. I believe the codes are based on your 2020 paper. Could you confirm whether this is a typo?

**Comment by mpaiao** [comment]
@Lo-hatch Thanks for catching it, and @xiangtaoxu thanks for working on the code! I almost never use the light-driven phenology, so I guess I this mistake managed to remain quiet for this long...

@xiangtaoxu I think your edits need a small fix because there isn't a cohort-level variable called leaf_turnover_rate. Let me see if I can fix it on top of your PR.

**Review by xiangtaoxu — APPROVED** [review]

**Comment by xiangtaoxu** [comment]
@mpaiao Thanks, I agree that using 12 / llspan is more appropriate here. BTW, @Lo-hatch found the bug and worked on the codes by her own and she should get all the credits.

@Lo-hatch I hope Marcos's edits make sense to you. Are you running the light-driven phenology scheme?

**Comment by mpaiao** [comment]
@xiangtaoxu indeed, I got confused with the review request and incorrectly assumed that you had edited it. 
Thanks @Lo-hatch for spotting the error and working on the bug fix, suggestions to improve and fix the code are always very appreciated.

**Comment by Lo-hatch** [comment]
> 



> @mpaiao Thanks, I agree that using 12 / llspan is more appropriate here. BTW, @Lo-hatch found the bug and worked on the codes by her own and she should get all the credits.
> 
> @Lo-hatch I hope Marcos's edits make sense to you. Are you running the light-driven phenology scheme?

no, I am not running this phenology scheme, just curious about the acclimation in ED. I am running a very simple version of sla acclimation to CO2.

**Pull request merged**
